project:
  type: website
website:
  reader-mode: true
  title: "Practical Labs CSA-40306 Ecological Modelling and Data Analysis in R"
  sidebar:
    style: "docked"
    collapse-level: 1
    search: true
    contents:
      - href: Lab1/no_solution.qmd
        text: "Lab 1"
      - href: Lab2/no_solution.qmd
        text: "Lab 2"
      - href: Lab3/no_solution.qmd
        text: "Lab 3"
      - href: Lab4/no_solution.qmd
        text: "Lab 4"
      - href: Lab6/no_solution.qmd
        text: "Lab 5 & 6"
      - href: Lab7/no_solution.qmd
        text: "Lab 7"
      - href: Lab9/no_solution.qmd
        text: "Lab 9"        
      - href: Lab10/no_solution.qmd
        text: "Lab 10"
      - href: Supplements/optim.qmd
        text: "Supplement: mle2 vs optim"         
      - href: Supplements/canned.qmd
        text: "Supplement: Canned methods"        
      - href: Supplements/bias_variance/no_solution.qmd
        text: "Supplement: Variance and bias of estimates"
      - section: "Solutions"
        contents:
          - href: Lab1/solution.qmd
            text: "Lab 1 (solutions)"
          - href: Lab2/solution.qmd
            text: "Lab 2 (solutions)"
          - href: Lab3/solution.qmd
            text: "Lab 3 (solutions)"
          - href: Lab4/solution.qmd
            text: "Lab 4 (solutions)"
          - href: Lab6/solution.qmd
            text: "Lab 5 & 6 (solutions)"
          - href: Lab7/solution.qmd
            text: "Lab 7 (solutions)"
          - href: Lab9/solution.qmd
            text: "Lab 9 (solutions)"             
          - href: Lab10/solution.qmd
            text: "Lab 10 (solutions)"
          - href: Supplements/bias_variance/solution.qmd
            text: "Variance and bias of estimates (solutions)"            
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true
