---
title: "Practical Labs CSA-40306 Ecological Modelling and Data Analysis"
---

Practical labs for the course [CSA-40306 Ecological Modelling and Data Analysis](https://studyhandbook.wur.nl/modules/CSA40306?type=Cursory) at Wageningen University.

Based on Ben Bolker's book [Ecological Models and Data in R](https://math.mcmaster.ca/~bolker/emdbook/index.html)
modified over the years by Bob Douma and Alejandro Morales.

**How to use these practical labs**

- Use the sidebar to navigate through the labs. These follow the different chapters in the
book (but not all chapters are covered in the course).

- Exercises are included throughout the labs as subheadings denoted [Exercise]{style="color:red; font-weight:bold;"}

- A copy of each lab is provided at the end of the sidebar with possible solutions. The
solutions are given after each [Exercise]{style="color:red; font-weight:bold;"} in their own
headings denoted [Solution]{style="color:green; font-weight:bold;"}.

- The output of the different code chunks are not given and this is on purpose to prevent
that you just read the material. You are meant to execute the code yourself and judge the
output. Please type the code yourself rather than copy-pasting. This may seem like a waste
of time but somehow the learning process is more effective when you actually type the code
yourself.

- If you suspect that something went wrong, please ask your colleagues and see if you can
figure out the problem together. Do not immediately ask the teachers.

**Note on how the labs have evolved over time**

The book by Benjamin Bolker is one of a kind and still very valuable to learn the
foundations of likelihood functions and the role they play in model-based inference in
ecology.

However, the code use in the book and R supplement are about 20 years old at the time of
writing. In the labs we have made our best efforts over the year to update the material
while at the same time maintaining some level of consistency.

Biggest changes include:

- Use of Stan for all the Bayesian modeling (labs 6, 7 and 9).

- Use of `ggplot2` and other tools from the `tidyverse` in parts of the labs.
