---
title: "Lab 5: Stochastic simulation"
author: Alejandro Morales & Bob Douma 2023
date: "October 23, 2023"
cache: true
visual: false
params:
  solution: false
filters:
  - custom-numbered-blocks
custom-numbered-blocks:
  groups:
    question:
      collapse: false
      colors: [00ff00, d9d9d9]
      label: "Exercise 4."
      boxstyle: foldbox.simple
    answer:
      collapse: false
      colors: [80bfff, d9d9d9]
      label: "Solution"
      boxstyle: foldbox.simple
  classes:
    Exercise:
      group: question
    Solution:
      group: answer
---

```{r setup, echo=FALSE}
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=5), tidy = TRUE)
```

# Learning goals
This lab has the goal to make yourself familiar with stochastic simulation. Stochastic simulation has a number of important goals. First, by using stochastic simulation and subsequently refitting a model to the simulated data, one can test if the parameters that were used to simulate the data can be retrieved, or whether the estimated parameters are biased. Secondly, one can use stochastic simulation as a form of model testing. By simulating from the model with the MLE parameters one can visually inspect whether the estimated model makes sense or whether it is biased in one form or another. For example, the model maybe well capable of describing the mean relationship between $x$ and $y$ but may not be able to capture the variation in $y$.

For stochastic simulation on needs a deterministic model (which in its simplest form is just a single number for the mean and a parameter related to the variance) and a stochastic model to describe the sample space (all possible outcomes) given the parameters. 


# Choosing probability distributions
In this exercise we revisit exercise 2.1 of lab 3. In that exercise we had six different datasets each describing a biological phenomenon. The first step was to choose a deterministic function that describes the mean effect of the predictor variable (x) on the response variable (y; Lab 3). The second step involved the choice of the stochastic distribution which describes how the data varies around the mean (Lab 4).

::: Exercise
Reload the first dataset, revisit the choice of your deterministic function, the eyeballed parameters, and the stochastic distribution. Next simulate data using these three components. Compare the simulated values with the observed values in a plot. 

:::

```{block2, echo = params$solution}
::: Solution

1. Dataset 1
if the first dataset is stored in a dataframe called shapes1, one can plot the observations as follows
plot(shapes1$y~ shapes1$x)

next one simulate from the data. If we assume the normal distribution to be reasonable choice, and a michaelis menten as a deterministic function, data can simulated as follows:
  
  y.sim <- rnorm(55,mean=(25*shapes1$x)/(60+shapes1$x),sd=1.5)

the standard deviation is quite hard to assess. One thing that one could do to estimate the standard deviation is to estimate the variation around the mean prediction. Roughly 2*sd gives the 95% confidence interval. As most of the datapoints seems to be within 3 points to the mean y, this would translate in an sd of ~ 1.5.


:::
```

